spring.datasource.url=jdbc:postgresql://localhost:5432/paicasso_db
spring.datasource.username=postgres
spring.datasource.password=root

sonarqube.url=http://localhost:9000
sonarqube.security.token=squ_532e010e206df7165cdffa61d12efc84f4889ae3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.frontend.url=http://localhost:5173
app.oauth2.redirect-path=/oauth2/redirect

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

app.jwt.secret=PaicassoSuperSecretKeyParaFirmaDeTokens1234567890!!
app.jwt.expiration-time=86400000