spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

sonarqube.url=${SONARQUBE_URL}
sonarqube.security.token=${SONARQUBE_SECURITY_TOKEN}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=false

app.frontend.url=${APP_FRONTEND_URL}
app.oauth2.redirect-path=/oauth2/redirect

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,repo

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-time=${APP_JWT_EXPIRATION_TIME}

server.forward-headers-strategy=framework