spring.datasource.url=jdbc:postgresql://localhost:5432/paicasso_db
spring.datasource.username=postgres
spring.datasource.password=root

sonarqube.url=http://localhost:9000
sonarqube.security.token=squ_67173f8360d8ba2c0aa60e9a475d435ac59efe03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.frontend.url=http://localhost:5173
app.oauth2.redirect-path=/oauth2/redirect

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,repo

app.jwt.secret=PaicassoSuperSecretKeyParaFirmaDeTokens1234567890!!
app.jwt.expiration-time=86400000